clc;
clear;
fs1=500e3;
f=10e3;
nCyl=5;
t1=0:1/fs:nCyl/f;
x=cos(2*pi*t*f);
subplot(411);
plot(t1, x1,'linewidth', 3);
title('Continious Signal');
xlabel('Time');
ylabel('Amplitude');

fs2=30e3;
t2=0:1/fs2:nCyl/f;
x2=cos(2*pi*t1*f);
subplot(412);
plot(t, x,'linewidth', 3);
title('Sampled Continious Signal at 30Hz');
xlabel('Time');
ylabel('Amplitude');
hold on;
stem(t2, x2, 'r', 'linewidth', 3);

fs3=70e3;
t3=0:1/fs3:nCyl/f;
x3=cos(2*pi*t3*f);
subplot(413);
plot(t, x, 'linewidth', 3);
title('Sampled Continious Signal at 70Hz');
xlabel('Time');
ylabel('Amplitude');
hold on;
stem(t3, x3, 'r', 'linewidth', 3);

fs4=15e3;
t4=0:1/fs4:nCyl/f;
x4=cos(2*pi*t4*f);
subplot(414);
plot(t, x, 'linewidth', 3);
title('Sampled Continious Signal at 15Hz');
xlabel('Time');
ylabel('Amplitude');
hold on;
stem(t4, x4, 'r', 'linewidth', 3);